### ISSUE TITLE
URI must contain a hostname

### ISSUE THREAD

**Issue by bebeboy** [Yukaii/KKBox-web-source#2]
I got this error - "URI must contain a hostname" when searching.  Any idea?

**Comment by Yukaii** [comment]
Hello, which version of Mp3Tag are you using? Also I'm not sure whether KKBox service is accessible outside Taiwan.

**Comment by bebeboy** [comment]
Hi Yukai,


Thanks for your reply.  I am using Mp3Tag version 2.8.   KKBox is accessible outside Taiwan I can search the lyrics or album etc from KKBox Taiwan.


Any idea which server is trying to connect with?


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Yukaii** [comment]
@bebeboy I've just updated the script three days ago according to the recent changes of KKBox website, could you please download the latest one and try again? 

Also, Mp3Tag writes a log file in [`c:\\debug_kkbox1.htm`](https://github.com/Yukaii/KKBox-web-source/blob/master/KKBox.src#L23) and [`c:\\debug_kkbox2.htm`](https://github.com/Yukaii/KKBox-web-source/blob/master/KKBox.src#L57), upload these file and paste searching keywords here so I can help with you. 😄

**Comment by bebeboy** [comment]
Hi Yukai,


I don't see any error this time with the latest version, but unfortunately no result returned. I have tried (e.g. Easons' U87 ) with the URL inside your script and it should return the correct album.  Just don't know why it doesn't work with the MP3TAG.


http://www.kkbox.com/tw/tc/search.php?search=album&word=U87


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Yukaii** [comment]
![screen shot 2017-06-07 at 8 56 56 pm](https://user-images.githubusercontent.com/4230968/26880005-9cb78e14-4bc5-11e7-8d24-6c721a99a15a.png)

I've tried this keyword without any problem, could you find  c:\\debug_kkbox1.htm and  c:\\debug_kkbox2.htm these two files and upload here?

**Comment by bebeboy** [comment]
I am not able to find the files you mentioned. Maybe blocked due to some security reason.   May I know which keyword used?  Not sure it's related to my location. Or I have directed to KKBox HK instead of Taiwan.

從我的 iPhone 傳送

Yukai Huang <notifications@github.com<mailto:notifications@github.com>> 於 2017年6月7日 21:12 寫道：


[screen shot 2017-06-07 at 8 56 56 pm]<https://user-images.githubusercontent.com/4230968/26880005-9cb78e14-4bc5-11e7-8d24-6c721a99a15a.png>

I've tried this keyword without any problem, could you find c:\debug_kkbox1.htm and c:\debug_kkbox2.htm these two files and upload here?

**Comment by Yukaii** [comment]
I used `U87` as the keyword. 

I think the HK version of KKBox is a possible reason. I've once tried to implement a proxy server for generating formatted JSON album data (under `/server` folder). But when I deployed to heroku, KKBox blocked my server since heroku server is in USA. KKBox might host a another version that have different HTML structure.

**Comment by bebeboy** [comment]
Thanks anyway. I am using iTunes.src. But kkbox cover more Chinese album for sure.

從我的 iPhone 傳送

Yukai Huang <notifications@github.com<mailto:notifications@github.com>> 於 2017年6月7日 22:44 寫道：


I used U87 as the keyword.

I think the HK version of KKBox is a possible reason. I've once tried to implement a proxy server for generating formatted JSON album data (under /server folder). But when I deployed to heroku, KKBox blocked my server since heroku server is in USA. KKBox might host a another version that have different HTML structure.

**Comment by bebeboy** [comment]
Hi Yukai,


May I know the following URL will return you a formatted JSON  like a text file?  Wanna make a HK version if I can. Please share me any KKBOX API  website if you have any.   Thanks !


<http://www.kkbox.com/tw/tc/search.php?search=album&word=><http://www.kkbox.com/hk/tc/search.php?search=album&word=%s>https://www.kkbox.com/tw/tc/search.php?search=album&word=u87


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Yukaii** [comment]
Currently `KKBox.src` script parses album information by looking up HTML of the search result page. As I know there's no public JSON API for searching KKBox music 😂 . Let me describe more on how to modify mp3tag web source script.

There are 2 parts in web source script (https://github.com/Yukaii/KKBox-web-source/blob/master/KKBox.src). The first part is for finding album(line 23-50), the second part is for parsing album information(line 59-149).

A typical development flow is as follows:

1. Search a album keyword in mp3tag (use a keyword for more than one album, otherwise mp3tag would skip the album selection popup)
1. The search result popup shows
1. Look into HTML source code of the search result (for example https://www.kkbox.com/tw/tc/search.php?search=album&word=apple)
1. Look into mp3tag debug file (`c:\\debug_kkbox1.htm`, you can change that path).
1. Use `findline`or `findinline` to locate album information in webpage. You would need to change the value of parameter. You can find the web source reference in [here](http://help.mp3tag.de/main_online.html).
1. Similar to album search result, modify the second part, check the debug file in `c:\\debug_kkbox2.htm`

**Comment by bebeboy** [comment]
Hi Yukaii,


I still have no chance to work with your kkbox script.  I have updated the path and now retrieved the debug_kkox1.htm.  See whether you can help with. Thanks.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by Yukaii** [comment]
@bebeboy Can you upload that file here? I could look into it when I have time.

**Comment by bebeboy** [comment]
Here is the file

[debug_kkbox1.txt](https://github.com/Yukaii/KKBox-web-source/files/1100820/debug_kkbox1.txt)

**Comment by Yukaii** [comment]
@bebeboy According to this debug output, your source script might not be the latest version. Try the latest one 😄

**Comment by bebeboy** [comment]
Just downloaded the latest script and it works now.  Thanks.
